usr/lib/python3/dist-packages/PyQt6/QtWebEngineCore.abi3.so
usr/lib/python3/dist-packages/PyQt6/QtWebEngineCore.pyi
usr/lib/python3/dist-packages/PyQt6/QtWebEngineQuick.abi3.so
usr/lib/python3/dist-packages/PyQt6/QtWebEngineQuick.pyi
usr/lib/python3/dist-packages/PyQt6/QtWebEngineWidgets.abi3.so
usr/lib/python3/dist-packages/PyQt6/QtWebEngineWidgets.pyi
usr/lib/python3/dist-packages/PyQt6_WebEngine-*.dist-info/INSTALLER
usr/lib/python3/dist-packages/PyQt6_WebEngine-*.dist-info/METADATA
